# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.provision :shell, privileged: true, path: "./start_server.sh"
end
